# Generated by Django 5.0.4 on 2024-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='yes', max_length=23),
            preserve_default=False,
        ),
    ]
